# maps department to list of aliases here
ALIASES = {'AC ENG': "",
'AFAM': "",
'ANATOMY': "",
'ANTHRO': "",
'ARABIC': "",
'ARMN': "",
'ART': "",
'ART HIS': "",
'ARTS': "",
'ASIANAM': "",
'BANA': "",
'BATS': "",
'BIO SCI': "",
'BIOCHEM': "",
'BME': "",
'BSEMD': "",
'CBE': "",
'CHC/LAT': "",
'CHEM': "",
'CHINESE': "",
'CLASSIC': "",
'CLT&THY': "",
'COGS': "",
'COM LIT': "",
'COMPSCI': "CS",
'CRITISM': "",
'CRM/LAW': "",
'CSE': "",
'DANCE': "",
'DEV BIO': "",
'DRAMA': "",
'EARTHSS': "",
'EAS': "",
'ECO EVO': "",
'ECON': "",
'ECPS': "",
'EDUC': "",
'EECS': "",
'ENGLISH': "",
'ENGR': "",
'ENGRCEE': "",
'ENGRMAE': "",
'ENGRMSE': "",
'EPIDEM': "",
'EURO ST': "",
'FIN': "",
'FLM&MDA': "",
'FRENCH': "",
'GEN&SEX': "",
'GERMAN': "",
'GLBL ME': "",
'GLBLCLT': "",
'GREEK': "",
'HEBREW': "",
'HISTORY': "",
'HUMAN': "",
'I&C SCI': "ICS",
'IN4MATX': "INF",
'INTL ST': "",
'ITALIAN': "",
'JAPANSE': "",
'KOREAN': "",
'LATIN': "",
'LINGUIS': "",
'LIT JRN': "",
'LPS': "",
'LSCI': "",
'M&MG': "",
'MATH': "",
'MGMT': "",
'MGMT EP': "",
'MGMT FE': "",
'MGMT HC': "",
'MGMTMBA': "",
'MGMTPHD': "",
'MOL BIO': "",
'MPAC': "",
'MUSIC': "",
'NET SYS': "",
'NEURBIO': "",
'NUR SCI': "",
'PATH': "",
'PED GEN': "",
'PERSIAN': "",
'PHARM': "",
'PHILOS': "",
'PHRMSCI': "",
'PHY SCI': "",
'PHYSICS': "",
'PHYSIO': "",
'POL SCI': "",
'PORTUG': "",
'PP&D': "",
'PSCI': "",
'PSYCH': "",
'PUB POL': "",
'PUBHLTH': "",
'REL STD': "",
'ROTC': "",
'RUSSIAN': "",
'SOC SCI': "",
'SOCECOL': "",
'SOCIOL': "",
'SPANISH': "",
'SPPS': "",
'STATS': "",
'SWE': "",
'UCDC': "",
'UNI AFF': "",
'UNI STU': "",
'UPPP': "",
'VIETMSE': "",
'VIS STD': "",
'WRITING': ""}